services:
  - name: django-api
    type: web
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn myapp.wsgi:application
    envVars:
      - key: DATABASE_URL
        sync: false
